#ifndef TP_LK_2D_MP_SHOOTER_COMMAND_H

enum Command{
    BUTTON_LEFT,
    BUTTON_RIGHT,
    BUTTON_UP,
    BUTTON_DOWN,
    MOUSE_ANGLE,
    COMMAND_RELOAD,
    COMMAND_SHOOT
};
#define TP_LK_2D_MP_SHOOTER_COMMAND_H

#endif //TP_LK_2D_MP_SHOOTER_COMMAND_H
